spring.application.name=gmahk

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/gmahk?useSSL=false&serverTimezone=Asia/Jakarta&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
app.jwt.secret=gmahkSecretKeyForJWTTokenGenerationMustBeAtLeast256BitsLongAndSecure!
app.jwt.expiration-ms=86400000

# Server
server.port=8080
server.servlet.context-path=/api

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
